version: 2
jobs:
  test:
    working_directory: ~/CircleCISample
    docker:
      - image: ahteshamdocker/myimage # (1)
    steps:
      - checkout
      - run: | # (5)  
          docker build -t andrewbestbier/ci-comparison-blog .  
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push andrewbestbier/ci-comparison-blog
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test