version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: ahteshamdocker/app # (1)
    steps:
      - checkout
      - run:
          name: Run tests # (3)
          command: 'git --version'
      - checkout
      - run: | # (5)    
          docker login -u $ahteshamdocker -p $realme@1234
          docker pull ahteshamdocker/app
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test