workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - build-env-vars
            - docker-hub-creds

jobs:
  build:
    docker:
      - image: ahteshamdocker/spring-boot-image
        auth:
          username: ahteshamdocker  # can specify string literal values
          password: realme@1234 
