version: 2.1
jobs:
  build:
    docker:
      - image: ahteshamdocker/app
        auth:
          username: ahteshamdocker
          password: realme@1234
    steps:
      - checkout
      - run: echo "testing"