version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.7
    steps:
      - run:
          name: Pull private Docker image
          command:
            systemctl enable docker.service
            systemctl start docker 
            docker login -u ahteshamdocker -p realme@1234
            docker pull ahteshamdocker/spring-boot-image:latest

