version: 2.1
jobs:
  build:
    docker:
      - image: ahteshamdocker/spring-boot-image
        auth:
          username: ahteshamdocker  # can specify string literal values
          password: realme@1234 
