version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      # Enable Docker-in-Docker
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      # Build the Docker image using the Dockerfile
      - run:
          name: Build Docker image
          command: docker build -t my-java-app .

      # Run tests or any other build steps as needed
      - run:
          name: Run Tests
          command: docker run my-java-app

