version: 2.1

orbs:
  my-orb: ahteshamahmad/job-build-deploy@0.0.1
jobs:
  my-job:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo "Hello, World!"
workflows:
  my-workflow:
    jobs:
      - my-job
          

