version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.7
        auth:
          username: ahteshamdocker
          password: realme@1234
    steps:
      - run:
          name: Pull private Docker image
          command: |
            docker pull ahteshamdocker/spring-boot-image:latest
