version: 2.1

orbs:
  job-build-deploy:
    description: "My custom orb"
    version: 1.0.0
    namespace: ahteshamahmad
    commands:
      hello:
        description: "Prints hello world"
        steps:
          - run: echo "Hello, world!"
    jobs:
      my-job:
        description: "My first job"
        executor: job-build-deploy/default
        steps:
          - job-build-deploy/my-job

workflows:
  my-workflow:
    jobs:
      - my-orb/my-job:
          context: my-context

